spring:
 application:
   name: clientservice
server:
     port: 8091
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
         defaultZone: http://localhost:8761/eureka
  instance: 
    hostname: localhost   
